2015-10-09 20:15:56,450 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager
2015-10-09 20:16:19,423 [lib.cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2015-10-09 20:16:19,461 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2015-10-09 20:18:59,387 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_y1UhF2/9a9d41878db77c8f406f05d1d8883b93ac83d8fc40c8f71b84b5a89d4434501d.bin" (task=1)
2015-10-09 20:18:59,555 [lib.cuckoo.core.scheduler] INFO: Task #1: acquired machine winxp-sp3 (label=winxp-sp3)
2015-10-09 20:18:59,920 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 9733 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/1/dump.pcap)
2015-10-09 20:19:24,390 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-10-09 20:22:33,049 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-10-09 20:22:45,048 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-10-09 20:22:45,335 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-10-09 20:22:45,513 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "ReportHTMLSummary":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 637, in process
    current.run(self.results)
  File "/root/cuckoo/modules/reporting/reporthtmlsummary.py", line 53, in run
    img = img.resize((150, 100), PIL.Image.ANTIALIAS)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1319, in resize
    self.load()
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 218, in load
    raise IOError("image file is truncated (%d bytes not processed)" % len(b))
IOError: image file is truncated (16 bytes not processed)
2015-10-09 20:22:45,569 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-10-09 20:22:47,959 [lib.cuckoo.core.scheduler] INFO: Task #1: reports generation completed (path=/root/cuckoo/storage/analyses/1)
2015-10-09 20:22:48,301 [lib.cuckoo.core.scheduler] INFO: Task #1: analysis procedure completed
2015-10-26 14:28:48,182 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager
2015-10-26 14:28:48,568 [lib.cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2015-10-26 14:28:48,577 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2015-10-27 11:03:48,936 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_8VeWMp/26a92873992b5a674ea953131a4effc119dee0bc74da8ffa43f4d8de7df3c169.bin" (task=2)
2015-10-27 11:03:49,054 [lib.cuckoo.core.scheduler] INFO: Task #2: acquired machine winxp-sp3 (label=winxp-sp3)
2015-10-27 11:03:49,182 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6281 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/2/dump.pcap)
2015-10-27 11:05:24,470 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-10-27 11:08:50,421 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-10-27 11:09:35,436 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-10-27 11:09:35,781 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-10-27 11:09:36,480 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-10-27 11:09:36,486 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-10-27 11:09:40,078 [lib.cuckoo.core.scheduler] INFO: Task #2: reports generation completed (path=/root/cuckoo/storage/analyses/2)
2015-10-27 11:09:40,154 [lib.cuckoo.core.scheduler] INFO: Task #2: analysis procedure completed
2015-10-27 18:50:52,360 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_2tTtBS/26a92873992b5a674ea953131a4effc119dee0bc74da8ffa43f4d8de7df3c169.bin" (task=3)
2015-10-27 18:50:52,373 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/26a92873992b5a674ea953131a4effc119dee0bc74da8ffa43f4d8de7df3c169"
2015-10-27 18:50:52,421 [lib.cuckoo.core.scheduler] INFO: Task #3: acquired machine winxp-sp3 (label=winxp-sp3)
2015-10-27 18:50:52,530 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 9717 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/3/dump.pcap)
2015-10-27 18:52:29,238 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-10-27 18:55:47,480 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-10-27 18:56:38,228 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-10-27 18:56:38,483 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-10-27 18:56:39,056 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-10-27 18:56:39,057 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-10-27 18:56:42,002 [lib.cuckoo.core.scheduler] INFO: Task #3: reports generation completed (path=/root/cuckoo/storage/analyses/3)
2015-10-27 18:56:42,078 [lib.cuckoo.core.scheduler] INFO: Task #3: analysis procedure completed
2015-10-28 10:01:41,359 [lib.cuckoo.core.scheduler] INFO: Starting analysis of URL "http://ckvip.cn-hangzhou.aliapp.com/sg/" (task=4)
2015-10-28 10:01:41,428 [lib.cuckoo.core.scheduler] INFO: Task #4: acquired machine winxp-sp3 (label=winxp-sp3)
2015-10-28 10:01:41,532 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 15977 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/4/dump.pcap)
2015-10-28 10:03:21,418 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-10-28 10:06:42,224 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-10-28 10:07:08,023 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-10-28 10:07:08,140 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-10-28 10:07:09,762 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-10-28 10:07:09,768 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-10-28 10:07:13,193 [lib.cuckoo.core.scheduler] INFO: Task #4: reports generation completed (path=/root/cuckoo/storage/analyses/4)
2015-10-28 10:07:13,250 [lib.cuckoo.core.scheduler] INFO: Task #4: analysis procedure completed
2015-10-28 10:25:46,453 [lib.cuckoo.core.scheduler] INFO: Starting analysis of URL "http://ckvip.cn-hangzhou.aliapp.com/sg/" (task=5)
2015-10-28 10:25:46,513 [lib.cuckoo.core.scheduler] INFO: Task #5: acquired machine winxp-sp3 (label=winxp-sp3)
2015-10-28 10:25:46,640 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 16561 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/5/dump.pcap)
2015-10-28 10:27:26,146 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-10-28 10:30:44,361 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-10-28 10:31:06,123 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-10-28 10:31:10,716 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-10-28 10:31:14,073 [lib.cuckoo.core.scheduler] INFO: Task #5: reports generation completed (path=/root/cuckoo/storage/analyses/5)
2015-10-28 10:31:14,149 [lib.cuckoo.core.scheduler] INFO: Task #5: analysis procedure completed
2015-11-05 16:29:07,602 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_zZRZY5/watson.zip" (task=6)
2015-11-05 16:29:07,679 [lib.cuckoo.core.scheduler] INFO: Task #6: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-05 16:29:07,801 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 27133 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/6/dump.pcap)
2015-11-05 16:31:24,138 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-05 16:32:37,759 [lib.cuckoo.core.scheduler] ERROR: Analysis failed: The package "modules.packages.zip" start function raised an error: Unable to execute the initial process, analysis aborted.
2015-11-05 16:32:40,828 [modules.processing.behavior] INFO: Analysis results folder does not contain any file or injection was disabled.
2015-11-05 16:32:45,682 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-05 16:32:46,587 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-05 16:32:46,898 [lib.cuckoo.core.scheduler] INFO: Task #6: reports generation completed (path=/root/cuckoo/storage/analyses/6)
2015-11-05 16:32:46,982 [lib.cuckoo.core.scheduler] INFO: Task #6: analysis procedure completed
2015-11-06 17:49:14,713 [lib.cuckoo.core.scheduler] INFO: Starting analysis of URL "http://ckvip.cn-hangzhou.aliapp.com/sg/" (task=7)
2015-11-06 17:49:14,775 [lib.cuckoo.core.scheduler] INFO: Task #7: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-06 17:49:14,874 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 4880 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/7/dump.pcap)
2015-11-06 17:51:28,067 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-06 17:54:45,686 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-06 17:55:25,429 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-06 17:55:30,706 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-06 17:55:33,856 [lib.cuckoo.core.scheduler] INFO: Task #7: reports generation completed (path=/root/cuckoo/storage/analyses/7)
2015-11-06 17:55:33,959 [lib.cuckoo.core.scheduler] INFO: Task #7: analysis procedure completed
2015-11-06 17:56:18,325 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_nMQVJp/watson.zip" (task=8)
2015-11-06 17:56:18,353 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/b5d91badce6095cd0a2a57c97dc8fd5f2eeab5e52259b4ae155544ec57eae836"
2015-11-06 17:56:18,410 [lib.cuckoo.core.scheduler] INFO: Task #8: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-06 17:56:18,593 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5382 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/8/dump.pcap)
2015-11-06 17:58:36,043 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-06 17:59:54,357 [lib.cuckoo.core.scheduler] ERROR: Analysis failed: The package "modules.packages.zip" start function raised an error: Unable to execute the initial process, analysis aborted.
2015-11-06 18:00:17,395 [modules.processing.behavior] INFO: Analysis results folder does not contain any file or injection was disabled.
2015-11-06 18:00:20,824 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-06 18:00:21,708 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-06 18:00:22,461 [lib.cuckoo.core.scheduler] INFO: Task #8: reports generation completed (path=/root/cuckoo/storage/analyses/8)
2015-11-06 18:00:22,512 [lib.cuckoo.core.scheduler] INFO: Task #8: analysis procedure completed
2015-11-06 18:08:55,757 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_g70Ohq/48763-3046.exe" (task=9)
2015-11-06 18:08:55,843 [lib.cuckoo.core.scheduler] INFO: Task #9: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-06 18:08:56,076 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5712 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/9/dump.pcap)
2015-11-06 18:11:10,949 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-06 18:14:29,573 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-06 18:15:00,924 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-06 18:15:01,093 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-06 18:15:01,270 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-06 18:15:01,271 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-06 18:15:03,088 [lib.cuckoo.core.scheduler] INFO: Task #9: reports generation completed (path=/root/cuckoo/storage/analyses/9)
2015-11-06 18:15:03,138 [lib.cuckoo.core.scheduler] INFO: Task #9: analysis procedure completed
2015-11-06 18:17:44,494 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_N9QYyL/<unknown>" (task=10)
2015-11-06 18:17:44,570 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_RZshAE/<unknown>.xml" (task=11)
2015-11-06 18:17:44,622 [lib.cuckoo.core.scheduler] INFO: Task #10: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-06 18:17:44,715 [lib.cuckoo.core.scheduler] INFO: Task #11: acquired machine win7-sp1-x64 (label=win7-sp1-x64)
2015-11-06 18:17:44,897 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5949 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/10/dump.pcap)
2015-11-06 18:17:44,972 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5950 (interface=virbr0, host=192.168.122.69, dump path=/root/cuckoo/storage/analyses/11/dump.pcap)
2015-11-06 18:19:12,205 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=win7-sp1-x64, ip=192.168.122.69)
2015-11-06 18:21:39,152 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-06 18:23:35,587 [lib.cuckoo.core.guest] INFO: win7-sp1-x64: analysis completed successfully
2015-11-06 18:24:53,918 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_ikLh4y/<unknown>" (task=12)
2015-11-06 18:24:59,227 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/b0dad8cf7af0445cd0eeb99dc6d8bc9e0e163067d08435d2f1cae6fe94984c16"
2015-11-06 18:25:04,244 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_lapbO2/<unknown>.xml" (task=13)
2015-11-06 18:25:04,518 [lib.cuckoo.core.scheduler] INFO: Task #12: acquired machine win7-sp1-x64 (label=win7-sp1-x64)
2015-11-06 18:25:05,196 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/0f6dc56d22db7232d87c3b16c057e74ea11a87ecdce32ca413de537349c8d900"
2015-11-06 18:25:09,701 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6124 (interface=virbr0, host=192.168.122.69, dump path=/root/cuckoo/storage/analyses/12/dump.pcap)
2015-11-06 18:26:58,734 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-06 18:27:13,677 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-06 18:27:17,041 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-06 18:27:17,111 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-06 18:27:27,449 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=win7-sp1-x64, ip=192.168.122.69)
2015-11-06 18:31:36,992 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-06 18:32:09,315 [lib.cuckoo.core.scheduler] INFO: Task #13: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-06 18:32:10,743 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6282 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/13/dump.pcap)
2015-11-06 18:32:37,616 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-06 18:32:43,563 [lib.cuckoo.core.scheduler] INFO: Task #11: reports generation completed (path=/root/cuckoo/storage/analyses/11)
2015-11-06 18:32:43,736 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-06 18:32:43,736 [lib.cuckoo.core.scheduler] INFO: Task #11: analysis procedure completed
2015-11-06 18:32:45,547 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-06 18:32:45,547 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-06 18:32:51,907 [lib.cuckoo.core.scheduler] INFO: Task #10: reports generation completed (path=/root/cuckoo/storage/analyses/10)
2015-11-06 18:32:52,149 [lib.cuckoo.core.scheduler] INFO: Task #10: analysis procedure completed
2015-11-06 18:34:51,318 [lib.cuckoo.core.guest] INFO: win7-sp1-x64: analysis completed successfully
2015-11-06 18:35:13,294 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-06 18:35:13,412 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-06 18:35:13,885 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-06 18:35:13,886 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-06 18:35:17,430 [lib.cuckoo.core.scheduler] INFO: Task #12: reports generation completed (path=/root/cuckoo/storage/analyses/12)
2015-11-06 18:35:17,518 [lib.cuckoo.core.scheduler] INFO: Task #12: analysis procedure completed
2015-11-06 18:35:42,106 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-06 18:39:02,210 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-06 18:39:18,112 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-06 18:39:18,230 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-06 18:39:19,229 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-06 18:39:19,230 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-06 18:39:22,878 [lib.cuckoo.core.scheduler] INFO: Task #13: reports generation completed (path=/root/cuckoo/storage/analyses/13)
2015-11-06 18:39:22,986 [lib.cuckoo.core.scheduler] INFO: Task #13: analysis procedure completed
2015-11-09 09:55:56,536 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_RQ9mf4/New Terms of Use (Naukrigulf).exe" (task=14)
2015-11-09 09:55:56,622 [lib.cuckoo.core.scheduler] INFO: Task #14: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-09 09:55:56,939 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 30373 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/14/dump.pcap)
2015-11-09 09:58:26,915 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-09 10:01:50,503 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-09 10:02:17,812 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-09 10:02:18,052 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-09 10:02:18,209 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-09 10:02:18,209 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-09 10:02:20,637 [lib.cuckoo.core.scheduler] INFO: Task #14: reports generation completed (path=/root/cuckoo/storage/analyses/14)
2015-11-09 10:02:20,726 [lib.cuckoo.core.scheduler] INFO: Task #14: analysis procedure completed
2015-11-09 14:27:49,664 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_SCxPgC/<unknown>" (task=15)
2015-11-09 14:27:49,733 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_2bNSQg/<unknown>.xml" (task=16)
2015-11-09 14:27:49,760 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/0f6dc56d22db7232d87c3b16c057e74ea11a87ecdce32ca413de537349c8d900"
2015-11-09 14:27:49,767 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/b0dad8cf7af0445cd0eeb99dc6d8bc9e0e163067d08435d2f1cae6fe94984c16"
2015-11-09 14:27:49,826 [lib.cuckoo.core.scheduler] INFO: Task #16: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-09 14:27:49,901 [lib.cuckoo.core.scheduler] INFO: Task #15: acquired machine win7-sp1-x64 (label=win7-sp1-x64)
2015-11-09 14:27:50,073 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 32220 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/16/dump.pcap)
2015-11-09 14:27:50,202 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 32221 (interface=virbr0, host=192.168.122.69, dump path=/root/cuckoo/storage/analyses/15/dump.pcap)
2015-11-09 14:29:17,066 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=win7-sp1-x64, ip=192.168.122.69)
2015-11-09 14:31:27,379 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-09 14:32:19,266 [lib.cuckoo.core.guest] INFO: win7-sp1-x64: analysis completed successfully
2015-11-09 14:34:28,787 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "BehaviorAnalysis":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 200, in process
    data = current.run()
  File "/root/cuckoo/modules/processing/behavior.py", line 1101, in run
    for call in process["calls"]:
  File "/root/cuckoo/modules/processing/behavior.py", line 191, in next
    return self.cacheless_next()
  File "/root/cuckoo/modules/processing/behavior.py", line 168, in cacheless_next
    self.wait_for_lastcall()
  File "/root/cuckoo/modules/processing/behavior.py", line 146, in wait_for_lastcall
    if not self.parser.read_next_message():
  File "/root/cuckoo/lib/cuckoo/common/netlog.py", line 195, in read_next_message
    self.handler.log_call(context, apiname, category, arguments)
  File "/root/cuckoo/modules/processing/behavior.py", line 252, in log_call
    returnval] + arguments)
  File "/root/cuckoo/modules/processing/behavior.py", line 311, in _parse
    pretty = pretty_print_arg(category, api_name, arg_name, argument["value"])
  File "/root/cuckoo/lib/cuckoo/common/utils.py", line 1186, in pretty_print_arg
    val = int(arg_val, 16)
ValueError: invalid literal for int() with base 16: '0x-7ffffffe'
2015-11-09 14:35:04,015 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/scheduler.py", line 414, in run
    self.process_results()
  File "/root/cuckoo/lib/cuckoo/core/scheduler.py", line 363, in process_results
    RunSignatures(task_id=self.task.id, results=results).run()
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 413, in run
    for proc in self.results["behavior"]["processes"]:
KeyError: 'behavior'
2015-11-09 14:41:45,487 [lib.cuckoo.core.scheduler] ERROR: winxp-sp3: guest communication timeout: unable to upload agent, check networking or try to increase timeout
2015-11-09 14:41:49,302 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path "/root/cuckoo/storage/analyses/16/logs".
2015-11-09 14:41:54,301 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-09 14:41:55,842 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-09 14:41:57,567 [lib.cuckoo.core.scheduler] INFO: Task #16: reports generation completed (path=/root/cuckoo/storage/analyses/16)
2015-11-09 14:41:57,822 [lib.cuckoo.core.scheduler] INFO: Task #16: analysis procedure completed
2015-11-09 14:43:49,704 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_N1_NNo/b0dad8cf7af0445cd0eeb99dc6d8bc9e0e163067d08435d2f1cae6fe94984c16.bin" (task=17)
2015-11-09 14:43:49,717 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/b0dad8cf7af0445cd0eeb99dc6d8bc9e0e163067d08435d2f1cae6fe94984c16"
2015-11-09 14:43:49,774 [lib.cuckoo.core.scheduler] INFO: Task #17: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-09 14:43:49,930 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 414 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/17/dump.pcap)
2015-11-09 14:46:17,428 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-09 14:49:37,726 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-09 14:50:14,372 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-09 14:50:15,088 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-09 14:50:16,211 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-09 14:50:16,212 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-09 14:50:21,004 [lib.cuckoo.core.scheduler] INFO: Task #17: reports generation completed (path=/root/cuckoo/storage/analyses/17)
2015-11-09 14:50:21,154 [lib.cuckoo.core.scheduler] INFO: Task #17: analysis procedure completed
2015-11-09 16:01:09,747 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_eDdXxB/test_word.doc" (task=18)
2015-11-09 16:01:09,914 [lib.cuckoo.core.scheduler] INFO: Task #18: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-09 16:01:10,038 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 1216 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/18/dump.pcap)
2015-11-09 16:03:36,885 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-09 16:05:30,413 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-09 16:05:44,110 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-09 16:05:44,226 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-09 16:05:44,782 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-09 16:05:44,782 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-09 16:05:47,898 [lib.cuckoo.core.scheduler] INFO: Task #18: reports generation completed (path=/root/cuckoo/storage/analyses/18)
2015-11-09 16:05:47,979 [lib.cuckoo.core.scheduler] INFO: Task #18: analysis procedure completed
2015-11-09 16:20:48,913 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_r49txs/<unknown>" (task=19)
2015-11-09 16:20:48,999 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_GJrGDk/<unknown>.xml" (task=20)
2015-11-09 16:20:49,003 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/0f6dc56d22db7232d87c3b16c057e74ea11a87ecdce32ca413de537349c8d900"
2015-11-09 16:20:49,003 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/b0dad8cf7af0445cd0eeb99dc6d8bc9e0e163067d08435d2f1cae6fe94984c16"
2015-11-09 16:20:49,099 [lib.cuckoo.core.scheduler] INFO: Task #20: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-09 16:20:49,174 [lib.cuckoo.core.scheduler] INFO: Task #19: acquired machine win7-sp1-x64 (label=win7-sp1-x64)
2015-11-09 16:20:49,323 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 1716 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/20/dump.pcap)
2015-11-09 16:20:49,387 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 1717 (interface=virbr0, host=192.168.122.69, dump path=/root/cuckoo/storage/analyses/19/dump.pcap)
2015-11-09 16:22:18,264 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=win7-sp1-x64, ip=192.168.122.69)
2015-11-09 16:24:22,913 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-09 16:25:05,720 [lib.cuckoo.core.guest] INFO: win7-sp1-x64: analysis completed successfully
2015-11-09 16:26:01,287 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "BehaviorAnalysis":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 200, in process
    data = current.run()
  File "/root/cuckoo/modules/processing/behavior.py", line 1101, in run
    for call in process["calls"]:
  File "/root/cuckoo/modules/processing/behavior.py", line 191, in next
    return self.cacheless_next()
  File "/root/cuckoo/modules/processing/behavior.py", line 168, in cacheless_next
    self.wait_for_lastcall()
  File "/root/cuckoo/modules/processing/behavior.py", line 146, in wait_for_lastcall
    if not self.parser.read_next_message():
  File "/root/cuckoo/lib/cuckoo/common/netlog.py", line 195, in read_next_message
    self.handler.log_call(context, apiname, category, arguments)
  File "/root/cuckoo/modules/processing/behavior.py", line 252, in log_call
    returnval] + arguments)
  File "/root/cuckoo/modules/processing/behavior.py", line 311, in _parse
    pretty = pretty_print_arg(category, api_name, arg_name, argument["value"])
  File "/root/cuckoo/lib/cuckoo/common/utils.py", line 1186, in pretty_print_arg
    val = int(arg_val, 16)
ValueError: invalid literal for int() with base 16: '0x-7ffffffe'
2015-11-09 16:26:14,640 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/scheduler.py", line 414, in run
    self.process_results()
  File "/root/cuckoo/lib/cuckoo/core/scheduler.py", line 363, in process_results
    RunSignatures(task_id=self.task.id, results=results).run()
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 413, in run
    for proc in self.results["behavior"]["processes"]:
KeyError: 'behavior'
2015-11-09 16:34:35,135 [lib.cuckoo.core.scheduler] ERROR: winxp-sp3: guest communication timeout: unable to upload agent, check networking or try to increase timeout
2015-11-09 16:34:39,002 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path "/root/cuckoo/storage/analyses/20/logs".
2015-11-09 16:34:43,048 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-09 16:34:44,467 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-09 16:34:46,476 [lib.cuckoo.core.scheduler] INFO: Task #20: reports generation completed (path=/root/cuckoo/storage/analyses/20)
2015-11-09 16:34:46,723 [lib.cuckoo.core.scheduler] INFO: Task #20: analysis procedure completed
2015-11-09 16:58:12,590 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_dVURJ4/<unknown>" (task=21)
2015-11-09 16:58:12,660 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/b0dad8cf7af0445cd0eeb99dc6d8bc9e0e163067d08435d2f1cae6fe94984c16"
2015-11-09 16:58:12,667 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_QvqAFo/<unknown>.xml" (task=22)
2015-11-09 16:58:12,752 [lib.cuckoo.core.scheduler] INFO: Task #21: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-09 16:58:12,764 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/0f6dc56d22db7232d87c3b16c057e74ea11a87ecdce32ca413de537349c8d900"
2015-11-09 16:58:13,018 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 2219 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/21/dump.pcap)
2015-11-09 17:00:45,339 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-09 17:04:08,446 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-09 17:04:10,323 [lib.cuckoo.core.scheduler] INFO: Task #22: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-09 17:04:10,475 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 2396 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/22/dump.pcap)
2015-11-09 17:04:25,001 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-09 17:04:25,118 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-09 17:04:25,989 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-09 17:04:25,990 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-09 17:04:35,113 [lib.cuckoo.core.scheduler] INFO: Task #21: reports generation completed (path=/root/cuckoo/storage/analyses/21)
2015-11-09 17:04:35,209 [lib.cuckoo.core.scheduler] INFO: Task #21: analysis procedure completed
2015-11-09 17:06:51,804 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-09 17:10:05,667 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-09 17:10:06,686 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_WRmLV4/74E5AE226710A.doc" (task=23)
2015-11-09 17:10:07,870 [lib.cuckoo.core.scheduler] INFO: Task #23: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-09 17:10:07,995 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 2533 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/23/dump.pcap)
2015-11-09 17:10:23,722 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-09 17:10:23,849 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-09 17:10:25,141 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-09 17:10:25,160 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-09 17:10:35,370 [lib.cuckoo.core.scheduler] INFO: Task #22: reports generation completed (path=/root/cuckoo/storage/analyses/22)
2015-11-09 17:10:35,438 [lib.cuckoo.core.scheduler] INFO: Task #22: analysis procedure completed
2015-11-09 17:12:40,817 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-09 17:14:39,753 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-09 17:15:03,391 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-09 17:15:03,542 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-09 17:15:04,292 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-09 17:15:04,293 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-09 17:15:09,569 [lib.cuckoo.core.scheduler] INFO: Task #23: reports generation completed (path=/root/cuckoo/storage/analyses/23)
2015-11-09 17:15:09,836 [lib.cuckoo.core.scheduler] INFO: Task #23: analysis procedure completed
2015-11-09 17:20:08,858 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_EZF1qa/<unknown>" (task=24)
2015-11-09 17:20:09,020 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_AfTHYt/<unknown>.xml" (task=25)
2015-11-09 17:20:09,024 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/b0dad8cf7af0445cd0eeb99dc6d8bc9e0e163067d08435d2f1cae6fe94984c16"
2015-11-09 17:20:09,025 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/0f6dc56d22db7232d87c3b16c057e74ea11a87ecdce32ca413de537349c8d900"
2015-11-09 17:20:09,094 [lib.cuckoo.core.scheduler] INFO: Task #24: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-09 17:20:09,260 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 2798 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/24/dump.pcap)
2015-11-09 17:22:35,909 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-09 17:25:55,408 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-09 17:26:16,633 [lib.cuckoo.core.scheduler] INFO: Task #25: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-09 17:26:17,022 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 2986 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/25/dump.pcap)
2015-11-09 17:26:31,111 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-09 17:26:31,484 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-09 17:26:31,944 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-09 17:26:31,945 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-09 17:26:40,072 [lib.cuckoo.core.scheduler] INFO: Task #24: reports generation completed (path=/root/cuckoo/storage/analyses/24)
2015-11-09 17:26:40,201 [lib.cuckoo.core.scheduler] INFO: Task #24: analysis procedure completed
2015-11-09 17:28:58,749 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-09 17:32:14,372 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-09 17:32:51,923 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-09 17:32:52,125 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-09 17:32:53,258 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-09 17:32:53,259 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-09 17:32:57,749 [lib.cuckoo.core.scheduler] INFO: Task #25: reports generation completed (path=/root/cuckoo/storage/analyses/25)
2015-11-09 17:32:57,801 [lib.cuckoo.core.scheduler] INFO: Task #25: analysis procedure completed
2015-11-10 15:18:57,247 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_AzLX_o/lxcglpx.exe" (task=26)
2015-11-10 15:18:57,333 [lib.cuckoo.core.scheduler] INFO: Task #26: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-10 15:18:57,626 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 12363 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/26/dump.pcap)
2015-11-10 15:21:29,530 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-10 15:22:54,151 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-10 15:23:02,516 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-10 15:23:02,637 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-10 15:23:02,793 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-10 15:23:02,794 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-10 15:23:03,367 [lib.cuckoo.core.scheduler] INFO: Task #26: reports generation completed (path=/root/cuckoo/storage/analyses/26)
2015-11-10 15:23:03,441 [lib.cuckoo.core.scheduler] INFO: Task #26: analysis procedure completed
2015-11-10 15:38:26,324 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_Ld6LR1/NRE&Scrap --Jully.xls" (task=27)
2015-11-10 15:38:26,406 [lib.cuckoo.core.scheduler] INFO: Task #27: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-10 15:38:26,538 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 12663 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/27/dump.pcap)
2015-11-10 15:40:58,620 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-10 15:44:13,657 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-10 15:44:20,687 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-10 15:44:20,818 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe6 in position 6: ordinal not in range(128)
2015-11-10 15:44:21,709 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe6 in position 6: ordinal not in range(128)
2015-11-10 15:44:21,710 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-10 15:44:23,289 [lib.cuckoo.core.scheduler] INFO: Task #27: reports generation completed (path=/root/cuckoo/storage/analyses/27)
2015-11-10 15:44:23,339 [lib.cuckoo.core.scheduler] INFO: Task #27: analysis procedure completed
2015-11-10 16:22:15,770 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_xbWgsR/CCCS.exe" (task=28)
2015-11-10 16:22:15,881 [lib.cuckoo.core.scheduler] INFO: Task #28: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-10 16:22:16,032 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 13223 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/28/dump.pcap)
2015-11-10 16:24:48,046 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-10 16:26:12,645 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-10 16:26:14,873 [modules.processing.behavior] INFO: Analysis results folder does not contain any file or injection was disabled.
2015-11-10 16:26:19,047 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-10 16:26:19,209 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-10 16:26:19,366 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-10 16:26:19,366 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-10 16:26:19,865 [lib.cuckoo.core.scheduler] INFO: Task #28: reports generation completed (path=/root/cuckoo/storage/analyses/28)
2015-11-10 16:26:19,932 [lib.cuckoo.core.scheduler] INFO: Task #28: analysis procedure completed
2015-11-11 15:34:47,243 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager
2015-11-11 15:34:47,924 [lib.cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2015-11-11 15:34:47,933 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2015-11-11 15:35:44,453 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_1couxY/PAYMENT.exe" (task=29)
2015-11-11 15:35:44,573 [lib.cuckoo.core.scheduler] INFO: Task #29: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-11 15:35:44,665 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 23198 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/29/dump.pcap)
2015-11-11 15:38:17,754 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-11 15:39:40,896 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-11 15:39:42,920 [modules.processing.behavior] INFO: Analysis results folder does not contain any file or injection was disabled.
2015-11-11 15:41:26,072 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-11 15:41:26,657 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-11 15:41:26,894 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-11 15:41:27,139 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-11 15:41:27,140 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-11 15:41:27,762 [lib.cuckoo.core.scheduler] INFO: Task #29: reports generation completed (path=/root/cuckoo/storage/analyses/29)
2015-11-11 15:41:27,825 [lib.cuckoo.core.scheduler] INFO: Task #29: analysis procedure completed
2015-11-11 15:50:43,110 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_GeQp3q/LATEST_ZeuS.exe" (task=30)
2015-11-11 15:50:43,197 [lib.cuckoo.core.scheduler] INFO: Task #30: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-11 15:50:43,457 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 23371 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/30/dump.pcap)
2015-11-11 15:53:19,994 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-11 15:55:31,882 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-11 15:55:38,508 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-11 15:55:38,879 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-11 15:55:40,615 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-11 15:55:40,733 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 15:55:41,072 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 15:55:41,072 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-11 15:55:42,388 [lib.cuckoo.core.scheduler] INFO: Task #30: reports generation completed (path=/root/cuckoo/storage/analyses/30)
2015-11-11 15:55:42,438 [lib.cuckoo.core.scheduler] INFO: Task #30: analysis procedure completed
2015-11-11 16:04:43,764 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_mbf9EN/boleto.exe" (task=31)
2015-11-11 16:04:43,832 [lib.cuckoo.core.scheduler] INFO: Task #31: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-11 16:04:43,947 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 23658 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/31/dump.pcap)
2015-11-11 16:07:24,829 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-11 16:10:40,035 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-11 16:10:46,771 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-11 16:10:47,015 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-11 16:10:48,481 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-11 16:10:48,618 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 16:10:48,785 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 16:10:48,786 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-11 16:10:49,702 [lib.cuckoo.core.scheduler] INFO: Task #31: reports generation completed (path=/root/cuckoo/storage/analyses/31)
2015-11-11 16:10:49,763 [lib.cuckoo.core.scheduler] INFO: Task #31: analysis procedure completed
2015-11-11 16:23:50,821 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_0IWi21/0483532497.exe" (task=32)
2015-11-11 16:23:50,890 [lib.cuckoo.core.scheduler] INFO: Task #32: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-11 16:23:50,974 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 23864 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/32/dump.pcap)
2015-11-11 16:26:29,545 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-11 16:29:42,454 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_1yU1p0/91023af7fab72e126fed4cdeaa5a8a2a.exe" (task=33)
2015-11-11 16:29:42,548 [lib.cuckoo.core.scheduler] INFO: Task #33: acquired machine win7-sp1-x64 (label=win7-sp1-x64)
2015-11-11 16:29:42,688 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 23995 (interface=virbr0, host=192.168.122.69, dump path=/root/cuckoo/storage/analyses/33/dump.pcap)
2015-11-11 16:29:44,289 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-11 16:30:00,103 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=win7-sp1-x64, ip=192.168.122.69)
2015-11-11 16:30:07,179 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-11 16:30:09,536 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-11 16:30:18,862 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-11 16:30:19,197 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 16:30:19,433 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 16:30:19,434 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-11 16:30:28,600 [lib.cuckoo.core.scheduler] INFO: Task #32: reports generation completed (path=/root/cuckoo/storage/analyses/32)
2015-11-11 16:30:28,681 [lib.cuckoo.core.scheduler] INFO: Task #32: analysis procedure completed
2015-11-11 16:32:39,896 [lib.cuckoo.core.guest] INFO: win7-sp1-x64: analysis completed successfully
2015-11-11 16:33:19,928 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-11 16:33:21,695 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-11 16:33:28,873 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-11 16:33:29,034 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 16:33:29,193 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 16:33:29,193 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-11 16:33:31,941 [lib.cuckoo.core.scheduler] INFO: Task #33: reports generation completed (path=/root/cuckoo/storage/analyses/33)
2015-11-11 16:33:32,007 [lib.cuckoo.core.scheduler] INFO: Task #33: analysis procedure completed
2015-11-11 16:40:30,990 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_fphnsh/octosetup.exe" (task=34)
2015-11-11 16:40:31,232 [lib.cuckoo.core.scheduler] INFO: Task #34: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-11 16:40:31,369 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 24188 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/34/dump.pcap)
2015-11-11 16:43:11,696 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-11 16:46:30,667 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-11 16:46:35,838 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-11 16:46:35,946 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-11 16:46:36,890 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-11 16:46:37,011 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 16:46:37,225 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 16:46:37,225 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-11 16:46:37,897 [lib.cuckoo.core.scheduler] INFO: Task #34: reports generation completed (path=/root/cuckoo/storage/analyses/34)
2015-11-11 16:46:37,980 [lib.cuckoo.core.scheduler] INFO: Task #34: analysis procedure completed
2015-11-11 16:51:20,383 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_Hae393/New Terms of Use (Naukrigulf).exe" (task=35)
2015-11-11 16:51:20,415 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/6e88242d1354c8ab4c2c02a287e203d491095abc93d806641ade44ad5074d6f6"
2015-11-11 16:51:20,468 [lib.cuckoo.core.scheduler] INFO: Task #35: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-11 16:51:20,649 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 24418 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/35/dump.pcap)
2015-11-11 16:53:56,066 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-11 16:57:14,138 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-11 16:57:39,373 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-11 16:57:40,863 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-11 16:57:46,941 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-11 16:57:47,118 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 16:57:47,276 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 16:57:47,277 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-11 16:57:49,380 [lib.cuckoo.core.scheduler] INFO: Task #35: reports generation completed (path=/root/cuckoo/storage/analyses/35)
2015-11-11 16:57:49,450 [lib.cuckoo.core.scheduler] INFO: Task #35: analysis procedure completed
2015-11-11 17:00:03,036 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_XhOcQV/9a9d41878db77c8f406f05d1d8883b93ac83d8fc40c8f71b84b5a89d4434501d.bin" (task=36)
2015-11-11 17:00:03,073 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/9a9d41878db77c8f406f05d1d8883b93ac83d8fc40c8f71b84b5a89d4434501d"
2015-11-11 17:00:03,129 [lib.cuckoo.core.scheduler] INFO: Task #36: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-11 17:00:03,396 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 24713 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/36/dump.pcap)
2015-11-11 17:02:42,057 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-11 17:06:06,629 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-11 17:06:33,218 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-11 17:06:33,456 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-11 17:06:34,946 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-11 17:06:35,123 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 17:06:35,566 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 17:06:35,566 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-11 17:06:36,188 [lib.cuckoo.core.scheduler] INFO: Task #36: reports generation completed (path=/root/cuckoo/storage/analyses/36)
2015-11-11 17:06:36,254 [lib.cuckoo.core.scheduler] INFO: Task #36: analysis procedure completed
2015-11-11 17:08:59,052 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_CRYgP1/24017856ae366df0764ca82978fb76e277b12fb30196555e338ab71a4f86ea21.bin" (task=37)
2015-11-11 17:08:59,146 [lib.cuckoo.core.scheduler] INFO: Task #37: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-11 17:08:59,292 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 25321 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/37/dump.pcap)
2015-11-11 17:11:36,375 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-11 17:14:50,937 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-11 17:14:57,795 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-11 17:14:58,880 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-11 17:15:03,562 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-11 17:15:03,681 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)
2015-11-11 17:15:03,975 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)
2015-11-11 17:15:03,976 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-11 17:15:05,673 [lib.cuckoo.core.scheduler] INFO: Task #37: reports generation completed (path=/root/cuckoo/storage/analyses/37)
2015-11-11 17:15:05,723 [lib.cuckoo.core.scheduler] INFO: Task #37: analysis procedure completed
2015-11-11 17:21:14,687 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_F47UxK/0fd98d4c9f293f077163af94e623d44908d0f645f0ce88fbf30c0868ff49888c.bin" (task=38)
2015-11-11 17:21:14,781 [lib.cuckoo.core.scheduler] INFO: Task #38: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-11 17:21:14,919 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 25686 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/38/dump.pcap)
2015-11-11 17:23:50,348 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-11 17:27:06,219 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-11 17:27:11,992 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-11 17:27:12,282 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-11 17:27:13,921 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-11 17:27:14,041 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-11 17:27:14,467 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-11 17:27:14,468 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-11 17:27:15,346 [lib.cuckoo.core.scheduler] INFO: Task #38: reports generation completed (path=/root/cuckoo/storage/analyses/38)
2015-11-11 17:27:15,397 [lib.cuckoo.core.scheduler] INFO: Task #38: analysis procedure completed
2015-11-11 17:40:49,714 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_W0AWKj/05f28b39a832c89e8555238fbdf91c65b3fe1893cb15baf20579c725843425ef.bin" (task=39)
2015-11-11 17:40:49,783 [lib.cuckoo.core.scheduler] INFO: Task #39: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-11 17:40:49,871 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 25977 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/39/dump.pcap)
2015-11-11 17:43:28,733 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-11 17:48:17,228 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-11 17:48:54,284 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-11 17:48:54,985 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-11 17:48:59,517 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-11 17:49:00,222 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-11 17:49:01,025 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-11 17:49:01,026 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-11 17:49:24,562 [lib.cuckoo.core.scheduler] INFO: Task #39: reports generation completed (path=/root/cuckoo/storage/analyses/39)
2015-11-11 17:49:24,790 [lib.cuckoo.core.scheduler] INFO: Task #39: analysis procedure completed
2015-11-11 17:53:50,792 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager
2015-11-11 17:53:51,728 [lib.cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2015-11-11 17:53:51,737 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2015-11-11 17:58:19,571 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager
2015-11-11 17:58:20,078 [lib.cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2015-11-11 17:58:20,087 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2015-11-11 18:01:38,696 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager
2015-11-11 18:01:39,323 [lib.cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2015-11-11 18:01:39,332 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2015-11-11 18:02:22,658 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_0XuCZH/0673bebeb70a9673068537d8073c1db16254a3498acd14e67d7f4496e49d68a1.bin" (task=40)
2015-11-11 18:02:22,798 [lib.cuckoo.core.scheduler] INFO: Task #40: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-11 18:02:22,959 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 26351 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/40/dump.pcap)
2015-11-11 18:05:20,998 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-11 18:07:19,804 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-11 18:07:28,628 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-11 18:07:29,881 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-11 18:07:34,676 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-11 18:07:34,896 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 18:07:35,533 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-11 18:07:35,533 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-11 18:07:39,068 [lib.cuckoo.core.scheduler] INFO: Task #40: reports generation completed (path=/root/cuckoo/storage/analyses/40)
2015-11-11 18:07:39,144 [lib.cuckoo.core.scheduler] INFO: Task #40: analysis procedure completed
2015-11-11 18:16:44,209 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager
2015-11-11 18:16:44,760 [lib.cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2015-11-11 18:16:44,770 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2015-11-12 10:40:44,161 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_knWZA9/ELLE013006.DOC" (task=41)
2015-11-12 10:40:44,269 [lib.cuckoo.core.scheduler] INFO: Task #41: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 10:40:44,402 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 902 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/41/dump.pcap)
2015-11-12 10:43:22,965 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 10:46:55,913 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 10:47:36,189 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 10:47:57,131 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 10:49:13,632 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 10:49:13,862 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 10:49:14,637 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 10:49:14,638 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 10:49:38,266 [lib.cuckoo.core.scheduler] INFO: Task #41: reports generation completed (path=/root/cuckoo/storage/analyses/41)
2015-11-12 10:49:38,466 [lib.cuckoo.core.scheduler] INFO: Task #41: analysis procedure completed
2015-11-12 14:04:58,138 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_FSInyF/0914_a_Blueweld_price_list.pdf" (task=42)
2015-11-12 14:04:58,233 [lib.cuckoo.core.scheduler] INFO: Task #42: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 14:04:58,323 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 2512 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/42/dump.pcap)
2015-11-12 14:07:46,077 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 14:11:03,115 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 14:11:15,423 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 14:11:17,644 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 14:11:25,807 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 14:11:25,927 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 14:11:26,592 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 14:11:26,593 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 14:11:30,506 [lib.cuckoo.core.scheduler] INFO: Task #42: reports generation completed (path=/root/cuckoo/storage/analyses/42)
2015-11-12 14:11:30,573 [lib.cuckoo.core.scheduler] INFO: Task #42: analysis procedure completed
2015-11-12 14:20:56,447 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_OEe3zt/GULF INQUIRY_18.gz" (task=43)
2015-11-12 14:20:56,516 [lib.cuckoo.core.scheduler] INFO: Task #43: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 14:20:56,620 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 2885 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/43/dump.pcap)
2015-11-12 14:23:42,366 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 14:24:59,585 [lib.cuckoo.core.scheduler] ERROR: Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.
2015-11-12 14:25:02,292 [modules.processing.behavior] INFO: Analysis results folder does not contain any file or injection was disabled.
2015-11-12 14:25:04,803 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 14:25:05,280 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 14:25:05,427 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-12 14:25:05,549 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-12 14:25:05,550 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 14:25:05,863 [lib.cuckoo.core.scheduler] INFO: Task #43: reports generation completed (path=/root/cuckoo/storage/analyses/43)
2015-11-12 14:25:05,925 [lib.cuckoo.core.scheduler] INFO: Task #43: analysis procedure completed
2015-11-12 14:37:56,266 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager
2015-11-12 14:37:56,761 [lib.cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2015-11-12 14:37:56,770 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2015-11-12 14:38:37,857 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_bxB7a9/LATEST_ZeuS.exe" (task=44)
2015-11-12 14:38:37,899 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/f1b14e419865272b35a573921cbdb4d646a47b89b439170bac48811f9266ab71"
2015-11-12 14:38:37,952 [lib.cuckoo.core.scheduler] INFO: Task #44: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 14:38:38,229 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 3259 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/44/dump.pcap)
2015-11-12 14:41:15,864 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 14:44:32,495 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 14:45:07,149 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/Mobile_Malware/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 14:45:07,367 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/Mobile_Malware/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 14:45:07,553 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/Mobile_Malware/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 14:45:09,230 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/Mobile_Malware/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 14:45:11,733 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 14:45:12,123 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 14:45:14,051 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 14:45:14,297 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 14:45:14,750 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 14:45:14,750 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 14:45:16,042 [lib.cuckoo.core.scheduler] INFO: Task #44: reports generation completed (path=/root/cuckoo/storage/analyses/44)
2015-11-12 14:45:16,120 [lib.cuckoo.core.scheduler] INFO: Task #44: analysis procedure completed
2015-11-12 15:11:54,937 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_mmWEJL/Stephanie_Phoebe_resume.doc" (task=45)
2015-11-12 15:11:55,014 [lib.cuckoo.core.scheduler] INFO: Task #45: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 15:11:55,247 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 3928 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/45/dump.pcap)
2015-11-12 15:14:36,543 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 15:18:17,668 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 15:18:24,465 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/Mobile_Malware/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 15:18:24,657 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/Mobile_Malware/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 15:18:25,012 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/Mobile_Malware/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 15:18:25,791 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/Mobile_Malware/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 15:18:28,347 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 15:18:28,532 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 15:18:30,030 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 15:18:30,231 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-12 15:18:30,835 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-12 15:18:30,836 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 15:18:32,404 [lib.cuckoo.core.scheduler] INFO: Task #45: reports generation completed (path=/root/cuckoo/storage/analyses/45)
2015-11-12 15:18:32,456 [lib.cuckoo.core.scheduler] INFO: Task #45: analysis procedure completed
2015-11-12 15:23:27,146 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_IZTC6H/Video of accident.EXE" (task=46)
2015-11-12 15:23:27,497 [lib.cuckoo.core.scheduler] INFO: Task #46: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 15:23:27,821 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 4150 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/46/dump.pcap)
2015-11-12 15:26:12,535 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 15:29:42,593 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 15:29:47,961 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/index_binaries.yar(197): can't open include file: /root/cuckoo/data/yara/Mobile_Malware/Android_malware_Dropper.yar
2015-11-12 15:29:49,869 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 15:29:50,077 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 15:29:51,497 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 15:29:51,700 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-12 15:29:51,998 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
2015-11-12 15:29:51,998 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 15:29:53,494 [lib.cuckoo.core.scheduler] INFO: Task #46: reports generation completed (path=/root/cuckoo/storage/analyses/46)
2015-11-12 15:29:53,555 [lib.cuckoo.core.scheduler] INFO: Task #46: analysis procedure completed
2015-11-12 15:30:43,387 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager
2015-11-12 15:30:44,015 [lib.cuckoo.core.scheduler] INFO: Loaded 2 machine/s
2015-11-12 15:30:44,024 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2015-11-12 15:32:36,018 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_I2Lkyv/05f28b39a832c89e8555238fbdf91c65b3fe1893cb15baf20579c725843425ef.bin" (task=47)
2015-11-12 15:32:36,059 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/05f28b39a832c89e8555238fbdf91c65b3fe1893cb15baf20579c725843425ef"
2015-11-12 15:32:36,129 [lib.cuckoo.core.scheduler] INFO: Task #47: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 15:32:36,257 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 4325 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/47/dump.pcap)
2015-11-12 15:35:18,819 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 15:38:38,973 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 15:39:03,452 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/binaries/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 15:39:03,643 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/binaries/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 15:39:03,819 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/binaries/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 15:39:03,994 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/binaries/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 15:39:05,255 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/binaries/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 15:39:08,489 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 15:39:09,352 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 15:39:12,948 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 15:39:13,233 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-12 15:39:14,139 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-12 15:39:14,139 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 15:39:16,265 [lib.cuckoo.core.scheduler] INFO: Task #47: reports generation completed (path=/root/cuckoo/storage/analyses/47)
2015-11-12 15:39:16,331 [lib.cuckoo.core.scheduler] INFO: Task #47: analysis procedure completed
2015-11-12 16:07:27,307 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_bjOwuh/5ijvq_1_.swf" (task=48)
2015-11-12 16:07:27,527 [lib.cuckoo.core.scheduler] INFO: Task #48: acquired machine win7-sp1-x64 (label=win7-sp1-x64)
2015-11-12 16:07:27,645 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 4895 (interface=virbr0, host=192.168.122.69, dump path=/root/cuckoo/storage/analyses/48/dump.pcap)
2015-11-12 16:07:43,190 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=win7-sp1-x64, ip=192.168.122.69)
2015-11-12 16:10:22,641 [lib.cuckoo.core.guest] INFO: win7-sp1-x64: analysis completed successfully
2015-11-12 16:10:24,403 [modules.processing.behavior] INFO: Analysis results folder does not contain any file or injection was disabled.
2015-11-12 16:10:25,391 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/binaries/Android_MalwareCertificates.yar(20): invalid field name "certificate"
2015-11-12 16:10:27,479 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 16:10:28,040 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 16:10:29,044 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 16:10:29,854 [lib.cuckoo.core.scheduler] INFO: Task #48: reports generation completed (path=/root/cuckoo/storage/analyses/48)
2015-11-12 16:10:29,992 [lib.cuckoo.core.scheduler] INFO: Task #48: analysis procedure completed
2015-11-12 16:26:25,566 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_fmuj7B/05f28b39a832c89e8555238fbdf91c65b3fe1893cb15baf20579c725843425ef.bin" (task=49)
2015-11-12 16:26:25,584 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/05f28b39a832c89e8555238fbdf91c65b3fe1893cb15baf20579c725843425ef"
2015-11-12 16:26:25,636 [lib.cuckoo.core.scheduler] INFO: Task #49: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 16:26:25,719 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5384 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/49/dump.pcap)
2015-11-12 16:29:06,675 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 16:32:25,781 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 16:32:49,848 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/binaries/vmdetect.yar(82): duplicated identifier "vmdetect"
2015-11-12 16:32:50,052 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/binaries/vmdetect.yar(82): duplicated identifier "vmdetect"
2015-11-12 16:32:50,269 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/binaries/vmdetect.yar(82): duplicated identifier "vmdetect"
2015-11-12 16:32:50,442 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/binaries/vmdetect.yar(82): duplicated identifier "vmdetect"
2015-11-12 16:32:51,209 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: /root/cuckoo/data/yara/binaries/vmdetect.yar(82): duplicated identifier "vmdetect"
2015-11-12 16:32:53,577 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 16:32:54,217 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 16:32:56,979 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 16:32:57,181 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 16:32:57,531 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 16:32:57,531 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 16:32:59,163 [lib.cuckoo.core.scheduler] INFO: Task #49: reports generation completed (path=/root/cuckoo/storage/analyses/49)
2015-11-12 16:32:59,227 [lib.cuckoo.core.scheduler] INFO: Task #49: analysis procedure completed
2015-11-12 16:52:39,286 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-zip-tmp/cuckoozip__WRzur/Banken.scr" (task=50)
2015-11-12 16:52:39,309 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/9a9d41878db77c8f406f05d1d8883b93ac83d8fc40c8f71b84b5a89d4434501d"
2015-11-12 16:52:39,363 [lib.cuckoo.core.scheduler] INFO: Task #50: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 16:52:39,627 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5901 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/50/dump.pcap)
2015-11-12 16:55:21,675 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 16:58:03,758 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 16:58:08,527 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 16:58:08,670 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 16:58:09,685 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 16:58:09,805 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 16:58:10,093 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 16:58:10,094 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 16:58:10,523 [lib.cuckoo.core.scheduler] INFO: Task #50: reports generation completed (path=/root/cuckoo/storage/analyses/50)
2015-11-12 16:58:10,581 [lib.cuckoo.core.scheduler] INFO: Task #50: analysis procedure completed
2015-11-12 16:59:11,856 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_VDtxEI/LATEST_ZeuS.exe" (task=51)
2015-11-12 16:59:11,880 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/f1b14e419865272b35a573921cbdb4d646a47b89b439170bac48811f9266ab71"
2015-11-12 16:59:11,933 [lib.cuckoo.core.scheduler] INFO: Task #51: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 16:59:12,209 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6174 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/51/dump.pcap)
2015-11-12 17:01:49,653 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 17:05:05,801 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 17:05:32,621 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 17:05:32,966 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 17:05:34,862 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 17:05:35,050 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 17:05:35,380 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 17:05:35,381 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 17:05:36,626 [lib.cuckoo.core.scheduler] INFO: Task #51: reports generation completed (path=/root/cuckoo/storage/analyses/51)
2015-11-12 17:05:36,700 [lib.cuckoo.core.scheduler] INFO: Task #51: analysis procedure completed
2015-11-12 17:09:31,736 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_k8reua/0483532497.exe" (task=52)
2015-11-12 17:09:31,769 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/06f12fe7bd28557a3d5aae70bcac0313caf72bf89ca2e9d1922a22726a89b54d"
2015-11-12 17:09:31,822 [lib.cuckoo.core.scheduler] INFO: Task #52: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 17:09:31,942 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6593 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/52/dump.pcap)
2015-11-12 17:12:13,550 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 17:15:32,519 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 17:16:35,603 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 17:16:38,534 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 17:16:49,509 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 17:16:49,715 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 17:16:49,900 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 17:16:49,900 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 17:16:55,209 [lib.cuckoo.core.scheduler] INFO: Task #52: reports generation completed (path=/root/cuckoo/storage/analyses/52)
2015-11-12 17:16:55,268 [lib.cuckoo.core.scheduler] INFO: Task #52: analysis procedure completed
2015-11-12 17:26:02,848 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_LFWpd0/Faturaniz.pdf" (task=53)
2015-11-12 17:26:02,924 [lib.cuckoo.core.scheduler] INFO: Task #53: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 17:26:03,035 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6929 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/53/dump.pcap)
2015-11-12 17:28:44,637 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 17:32:04,904 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 17:32:39,842 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 17:32:58,379 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 17:33:57,983 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 17:33:58,103 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 17:33:58,651 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 17:33:58,653 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 17:34:21,525 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-zip-tmp/cuckoozip_r9MLRM/service.exe" (task=54)
2015-11-12 17:34:21,693 [lib.cuckoo.core.scheduler] INFO: Task #54: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 17:34:22,320 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 7156 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/54/dump.pcap)
2015-11-12 17:34:23,520 [lib.cuckoo.core.scheduler] INFO: Task #53: reports generation completed (path=/root/cuckoo/storage/analyses/53)
2015-11-12 17:34:23,647 [lib.cuckoo.core.scheduler] INFO: Task #53: analysis procedure completed
2015-11-12 17:37:11,681 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 17:40:39,983 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 17:40:51,381 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 17:40:53,297 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 17:41:00,731 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 17:41:00,903 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)
2015-11-12 17:41:01,149 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)
2015-11-12 17:41:01,150 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 17:41:03,530 [lib.cuckoo.core.scheduler] INFO: Task #54: reports generation completed (path=/root/cuckoo/storage/analyses/54)
2015-11-12 17:41:03,592 [lib.cuckoo.core.scheduler] INFO: Task #54: analysis procedure completed
2015-11-12 17:42:48,255 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-zip-tmp/cuckoozip_L41T9F/write lorisidae.exe" (task=55)
2015-11-12 17:42:48,342 [lib.cuckoo.core.scheduler] INFO: Task #55: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-12 17:42:48,493 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 7396 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/55/dump.pcap)
2015-11-12 17:45:30,319 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-12 17:46:51,182 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-12 17:46:57,300 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "antivm_vmware_libs":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 427, in run
    result = sig.on_call(call, proc)
  File "/root/cuckoo/modules/signatures/antivm_vmware_libs.py", line 39, in on_call
    ignorecase=True):
TypeError: check_argument_call() got an unexpected keyword argument 'ignorecase'
2015-11-12 17:46:57,319 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-12 17:46:57,916 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-12 17:46:58,127 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 17:46:58,296 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
2015-11-12 17:46:58,296 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-12 17:46:58,507 [lib.cuckoo.core.scheduler] INFO: Task #55: reports generation completed (path=/root/cuckoo/storage/analyses/55)
2015-11-12 17:46:58,565 [lib.cuckoo.core.scheduler] INFO: Task #55: analysis procedure completed
2015-11-13 11:40:54,153 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_cAzZg6/signtool.exe" (task=56)
2015-11-13 11:40:54,284 [lib.cuckoo.core.scheduler] INFO: Task #56: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-13 11:40:54,677 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 15194 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/56/dump.pcap)
2015-11-13 11:43:44,578 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-13 11:45:10,960 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-13 11:45:18,813 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-13 11:45:19,883 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-13 11:45:20,072 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTML" returned the following error: Failed to generate HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-13 11:45:20,371 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportHTMLSummary" returned the following error: Failed to generate summary HTML report: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
2015-11-13 11:45:20,372 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-13 11:45:22,676 [lib.cuckoo.core.scheduler] INFO: Task #56: reports generation completed (path=/root/cuckoo/storage/analyses/56)
2015-11-13 11:45:22,768 [lib.cuckoo.core.scheduler] INFO: Task #56: analysis procedure completed
2015-11-13 17:50:02,544 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_9qC1OX/5ijvq_1_.swf" (task=57)
2015-11-13 17:50:02,702 [lib.cuckoo.core.scheduler] INFO: File already exists at "/root/cuckoo/storage/binaries/96aa13956a27e1c392fbb7139fb793d1492107ef0901453697c35550e316ac07"
2015-11-13 17:50:02,788 [lib.cuckoo.core.scheduler] INFO: Task #57: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-13 17:50:02,867 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 17600 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/57/dump.pcap)
2015-11-13 17:52:49,793 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-13 17:56:18,244 [lib.cuckoo.core.guest] INFO: winxp-sp3: analysis completed successfully
2015-11-13 17:56:40,430 [modules.processing.behavior] INFO: Analysis results folder does not contain any file or injection was disabled.
2015-11-13 17:56:46,478 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-13 17:56:47,724 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-13 17:56:49,251 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-13 17:56:50,940 [lib.cuckoo.core.scheduler] INFO: Task #57: reports generation completed (path=/root/cuckoo/storage/analyses/57)
2015-11-13 17:56:50,997 [lib.cuckoo.core.scheduler] INFO: Task #57: analysis procedure completed
2015-11-16 09:02:41,022 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_KWrOFV/Purchase Information.jar" (task=58)
2015-11-16 09:02:41,099 [lib.cuckoo.core.scheduler] INFO: Task #58: acquired machine winxp-sp3 (label=winxp-sp3)
2015-11-16 09:02:41,195 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 9213 (interface=virbr0, host=192.168.122.23, dump path=/root/cuckoo/storage/analyses/58/dump.pcap)
2015-11-16 09:05:36,706 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=winxp-sp3, ip=192.168.122.23)
2015-11-16 09:06:49,940 [lib.cuckoo.core.scheduler] ERROR: Analysis failed: The package "modules.packages.jar" start function raised an error: Unable to find any Java executable.
2015-11-16 09:06:54,885 [modules.processing.behavior] INFO: Analysis results folder does not contain any file or injection was disabled.
2015-11-16 09:06:58,658 [lib.cuckoo.core.plugins] ERROR: Failed run on_complete() method for signature "kibex_behavior":
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/plugins.py", line 453, in run
    result = sig.on_complete()
  File "/root/cuckoo/modules/signatures/kibex_apis.py", line 74, in on_complete
    if self.check_started_service(service):
AttributeError: 'Kibex_APIs' object has no attribute 'check_started_service'
2015-11-16 09:06:59,239 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory
2015-11-16 09:07:00,070 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Weasyprint Python library is not installed
2015-11-16 09:07:00,578 [lib.cuckoo.core.scheduler] INFO: Task #58: reports generation completed (path=/root/cuckoo/storage/analyses/58)
2015-11-16 09:07:00,647 [lib.cuckoo.core.scheduler] INFO: Task #58: analysis procedure completed
